title: "SDK Release Notes"
description: "What’s New in Our SDK – Bold Moves, Smarter Code."
baseurl: "/Doc_Release_Note" # Adjust if your repository name differs
url: "https://betterapptech.github.io"

theme: jekyll-theme-cayman
