title: "SDK Release Notes"
description: "Public release notes for our SDK"
baseurl: "/Doc_Release_Note" # Adjust if your repository name differs
url: "https://betterapptech.github.io"

theme: jekyll-theme-cayman
